This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./tfg.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file tfg.acn....done (43 entries accepted, 0 rejected).
Sorting entries....done (237 comparisons).
Generating output file tfg.acr....done (90 lines written, 0 warnings).
Output written in tfg.acr.
Transcript written in tfg.alg.
